apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20231026144753.0.0+build.02e9424
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20231026144753.0.0+build.02e9424
  releaseNotes: |
    Release v20231026144753.0.0+build.02e9424 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-26-10-2023-10-37-14-139774830/where-for-dinner-search-my-apps-bundle@sha256:f5ab40b835f756d50357753e5e871565b7e0735edae7ef0d2873c4a4ff828947
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

