apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20231026144737.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20231026144737.0.0+build.02e9424
  releaseNotes: |
    Release v20231026144737.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-26-10-2023-10-37-14-139774830/where-for-dinner-my-apps-bundle@sha256:6c1de9716c1a583e39b6be844892ff665d4169e446e3574f83b22d9eb5186c35
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

