apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20231026144815.0.0+build.02e9424
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20231026144815.0.0+build.02e9424
  releaseNotes: |
    Release v20231026144815.0.0+build.02e9424 of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-26-10-2023-10-37-14-139774830/where-for-dinner-search-proc-my-apps-bundle@sha256:1d40edd7247f17f4695c7d5fd5a308efb4bb5ec47a3958ab074389c6e81502f1
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

